CC = cc

AR = ar rcs

RM = rm -f

NAME = libft.a

CFLAGS = -Wall -Wextra -Werror

SRCS = libft/ft_atoi.c \
       libft/ft_bzero.c \
       libft/ft_calloc.c \
       libft/ft_isalnum.c \
       libft/ft_isalpha.c \
       libft/ft_isascii.c \
       libft/ft_isdigit.c \
       libft/ft_isprint.c \
       libft/ft_itoa.c \
       libft/ft_memchr.c \
       libft/ft_memcmp.c \
       libft/ft_memcpy.c \
       libft/ft_memmove.c \
       libft/ft_memset.c \
       libft/ft_putchar_fd.c \
       libft/ft_putendl_fd.c \
       libft/ft_putnbr_fd.c \
       libft/ft_putstr_fd.c \
       libft/ft_split.c \
       libft/ft_strchr.c \
       libft/ft_strdup.c \
       libft/ft_striteri.c \
       libft/ft_strjoin.c \
       libft/ft_strlcat.c \
       libft/ft_strlcpy.c \
       libft/ft_strlen.c \
       libft/ft_strmapi.c \
       libft/ft_strncmp.c \
       libft/ft_strnstr.c \
       libft/ft_strrchr.c \
       libft/ft_strtrim.c \
       libft/ft_substr.c \
       libft/ft_tolower.c \
       libft/ft_toupper.c \
       ft_printf.c \
       ft_printf_utils.c \
       ft_uitoa.c \
       ft_printf_utils_hex.c \
       ft_hextoa.c

BONUS_SRCS = libft/ft_lstadd_back_bonus.c \
             libft/ft_lstadd_front_bonus.c \
             libft/ft_lstclear_bonus.c \
             libft/ft_lstdelone_bonus.c \
             libft/ft_lstiter_bonus.c \
             libft/ft_lstlast_bonus.c \
             libft/ft_lstmap_bonus.c \
             libft/ft_lstnew_bonus.c \
             libft/ft_lstsize_bonus.c

OBJS = $(SRCS:.c=.o)

B_OBJS = $(BONUS_SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(AR) $(NAME) $(OBJS)

clean:
	$(RM) $(OBJS) $(B_OBJS) meow

fclean: clean
	$(RM) $(NAME)

re: fclean all

bonus: meow

meow: $(B_OBJS) $(OBJS)
	$(AR) $(NAME) $(OBJS) $(B_OBJS)
	touch meow

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@
